apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexkart-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/sqlite/data"