apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-categories-service-deployment
  labels:
    app: product-categories-service
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-categories-service
      version: v1.0
  template:
    metadata:
      labels:
        app: product-categories-service
        version: v1.0
    spec:
      containers:
        - name: product-categories-service
          image: svrajasekar/flexkart-product-categories-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9003
          volumeMounts:
            - mountPath: /data
              name: flexkart-pv-storage
      volumes:
        - name: flexkart-pv-storage
          persistentVolumeClaim:
            claimName: flexkart-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: product-categories-service
spec:
  selector:
    app: product-categories-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9003
